var labels = {
    lblTitle: ["Land Degradation Neutrality DSS Haiti", "SSD para la Neutralidad en la Degradadción de la Tierra en Haiti"],
     lblExpl1: ["This platform aims to support decision-making to achieve Land Degradation Neutrality in Haiti by identifying priority areas for the implementation of sustainable management practices and the integration of qualitative and quantitative indicators relevant to the monitoring and evaluation of land degradation.",
        "Esta plataforma está siendo desarrollada con el objetivo de contribuir a la visualización y caracterización de la línea de base y la  identificación de zonas prioritarias para la implementación de prácticas sustentables de manejo. La plataforma facilita la exploración y consulta integrada de indicadores cualitativos y cuantitativos relevantes para el monitoreo y evaluación de la degradación de las tierras."],
   
    lblAOIMask: ["AOI mask", "AOI mask"],
    lblAnnualNDVI: ["Annual Mean NDVI MODIS (MOD13Q1)", "NDVI Anual MODIS(MOD13Q1)"],
    lblAppDeveloped: ["For questions and feedback please contact:  ",
        "Para preguntas o sugerencias por favor contactar a:"],
    lblArea: ["Area", "Área"],
    lblAreaName: ["Name", "Nombre"],
    lblArtificial: ["Artificial", "Artificial"],
    lblAssetClick: ["Select which layer you want to click on: ", "Seleccione en qué capa desea hacer click: "],
    lblAssetId: ["GEE asset id", "Id de asset en GEE"],
    lblBareGround: ["Bare Ground", "Suelo Desnudo"],
    lblBasins: ["Basins", "Cuencas"],
    lblBigImage: ["It is not posible to download generated image.", "No es posible descargar la imagen generada."],
    lblBuiltArea: ["Built Area", "Área construida"],
    lblCalendarYear: ["Calendar year", "Año calendario"],
    lblCloseInfoPanel: ["Close info panel", "Cerrar panel informativo"],
    lblClouds: ["Clouds", "Nubes"],

    lblCombinedCategoriesArea: ["Combined categories area ", "Superficie de la combinación"],
    lblCropland: ["Cropland", "Cultivos"],
    lblCrops: ["Crops", "Cultivos"],
    lblCurrentLC: ["To Land Cover", "Hasta Uso"],
    lblCustomAsset: ["Custom GEE asset", "Asset propio en GEE"],
    lblCustomLayer: [
        "1- What will you map? Enter the name and click '+' button. Layer will be added to the map",
        "1- ¿Qué mapearás? Ingresa un nombre y haz click en el botón '+'. Una capa con el nombre ingresado se agregará al mapa."
    ],
    lblDeclining: ["Declining", "Disminución"],
    lblDecliningProductivity: ["Declining productivity", "Productividad decreciente"],
    lblDeforestation: ["Deforestation (Ha)", "Deforestación (Ha)"],
    lblDegradation: ["Degradation", "Degradación"],
    lblDifference: ["Difference", "Diferencia"],
    lblDisclaimer: [
        "The boundaries and names shown and the designations used on this map do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers and boundaries",
        "The boundaries and names shown and the designations used on this map do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers and boundaries"
    ],
    lblDisplay: ["Calculate", "Calclular"],
    lblDownload: ["Download combined layer as tif", "Descargar la capa combinada como tif"],
    lblDownloadCsv: ["Download as csv", "Descargar como csv"],
    lblDownloadFileName: ["Drawn-features", "Elementos-dibujados"],
    lblDownloadLinks: [
        "4- Download your polygons and points (links appear and are updated while drawing)",
        "4- Descarga los polígonos y puntos (los links aparecen abajo y son actualizados mientras se dibuja)"
    ],
    lblDrawFeatures: [
        "2- Select the drawing tool (point or polygon) and draw on the map by clicking",
        "2- Selecciona la herramienta de dibujo (punto o polígono) y dibuja en el mapa haciendo click"
    ],
    lblDrawingTools: ["Drawing tool", "Herramienta de dibujo"],
    lblDrawnFeature: ["Drawn-feature in: ", "Elemento dibujado en: "],
    lblESRI: ["ESRI", "ESRI"],
    lblEarlySignDecline: ["Early sign of decline", "Deterioro Incipiente"],
    lblElevation: ["Elevation", "Elevación"],
    lblEnterAssetId: ["Alternatively, if you want to calculate stats for a preloaded asset please enter the asset id and click on the button to load it from GEE. If the asset contains more than one feature, the first one will be processed",
        "Opcionalmente, si desea calcular indicadores para un asset ya disponible en GEE ingrese el id de dicho asset y haga click en el botón 'Cargar' para procesarlo. Si el asset contiene más de una feature, se procesará la primera."],
    lblErrorCalculating: ["An error occurred while calculating area. Please try again or select a smaller area.", "Ocurrió un error al calcular el área. Por favor inténtelo de nuevo o seleccione un área de menor tamaño."],
    lblExpl2: ["Choose a Governorates from the list below or click on the map to get statistics.",
        "Seleccione un Governorate de la lista o haga click en el mapa para obtener estadísticas."],
    lblExploreCharts: ["Open each section below to explore the available charts for the selected area of interest.", "Open each section below to explore the available charts for the selected area of interest."],
    lblExploreLayers: ["Open each section below to explore the related layers and load or remove them from the map.", "Open each section below to explore the related layers and load or remove them from the map."],
    lblFireIndex: ["Fire index (Recurrence 2001-2023)", "Índice de fuego (recurrencia 2001-2023)"],
    lblFloodedVegetation: ["Flooded Vegetation", "Vegetación inundada"],
    lblFlyTo: ["Go", "Ir"],
    lblFlyToText: [
        "Enter lat/lon and press 'Go' if you want to add a marker and zoom in.",
        "Ingrese lat/lon y presione 'Ir' si desea agregar un marcador y hacer zoom en ese punto."],
    lblFromLC: ["From Land Cover", "Desde Uso"],
    lblGains: ["Gains", "Ganancias"],
    lblGeneralCharts: ["General Charts", "Gráficos generales"],
    lblGeneralLayers: ["General layers", "General layers"],
    lblGeneratingCharts: ["Generating chart ", "Generando gráfico "],
    lblGeneratingDownloadLink: ["Generating download link...", "Generando link de descarga..."],
    lblGeometryNotContained: ["Geometry has to be contained in country area.", "La geometría debe estar contenida en el área del país."],
    lblGetStatistics: [
        "3- Select a polygon in the map (using the hand icon) and click the button below to obtain statistics for the area.",
        "3- Selecciona un polígono en el mapa (utilizando el ícono de la mano) y haz click en el botón de abajo para obtener estadísticas para el área."
    ],
    lblGrassland: ["Grassland", "Pastizal/Arbustal"],
    lblHotspots: ["Multi-Criteria analysis", "Análisis de Multicriterio"],
    lblHotspotsCharts: ["Combined LC/LPD/SOC Charts", "Gráficos con CS/DPV/COS combinados"],
    lblImprovement: ["Improvement", "Mejora"],
    lblIncreasing: ["Increasing", "Aumento"],
    lblIncreasingProductivity: ["Increasing productivity", "Productividad creciente"],
    lblInvalidAssetId: ["Invalid GEE asset id", "Id de asset en GEE inválido"],
    lblKBANonProtected: ["KBA non protected", "KBA no protegida"],
    lblKBAProtected: ["KBA protected", "KBA protegida"],
    lblKba: ["KBA", "KBA"],
    lblKeyBiodiversityArea: ["Key Biodiversity Area", "Área clave de biodiversidad"],
    lblKeyBiodiversityAreas: ["Key Biodiversity Areas", "Áreas clave de biodiversidad"],
    lblLCESA: ["ESA", "ESA"],
    lblLCPieChartChange: ["Land Cover change", "Cambio de Uso del Suelo"],
    lblLDNImplementation: ["LDN project", "LDN project"],
    lblLPDperLC: ["LPD per LC", "Productividad x Uso"],
    lblLandCover: ["Land Cover", "Cobertura del Suelo"],
    lblLandProductivityDynamics: ["Land Productivity Dynamics (2001-2023)", "Dinámica de la Productividad Vegetal (2001-2023)"],
    lblLatitude: ["Lat.", "Lat."],
    lblLayerName: ["Layer Name", "Nombre de la capa"],
    lblLevel1: ["Governorates", "Governorates"],
    lblLevel2: ["Districts", "Municipios"],
    lblLinks: ["Links", "Links"],
    lblLoadAsset: ["Load", "Cargar"],
    lblLoading: ["Loading...", "Cargando..."],
    lblLoadingLevel2: ["Loading districts...", "Cargando municipios..."],
    lblLocNotSupported: ["Device geolocalization is not not supported for this browser/OS.",
        "La geolocalización del dispositivo no está disponible para el navegador/SO"],
    lblLongitude: ["Lon.", "Lon."],
    lblLosses: ["Losses", "Pérdidas"],
    lblMonthlyNDVI: ["Monthly NDVI MODIS(MOD13Q1)", "NDVI Mensual MODIS(MOD13Q1)"],
    lblMoreThanOneFeature: ["The preloaded asset must contain only one feature", "El asset debe contener un único feature"],
    lblMountain1: ["≥ 4500m", "≥ 4500m"],
    lblMountain2: ["3500-4500m", "3500-4500m"],
    lblMountain3: ["2500-3500m", "2500-3500m"],
    lblMountain4: ["1500-2500m slope ≥2°", "1500-2500m slope ≥2°"],
    lblMountain5: ["1000-1500m slope ≥5°", "1000-1500m slope ≥5°"],
    lblMountain6: ["300-1000m LER >300m", "300-1000m LER >300m"],
    lblMountain7: ["Inner plateau <25km2", "Inner plateau <25km2"],
    lblMountainCoverage: ["Mountain Coverage", "Cobertura de montaña"],
    lblMountains: ["Mountains", "Montañas"],
    lblNPP: ["Net Primary Productivity 2022", "Poductividad Primarria Neta 2022"],
    lblNPPLegend: ["Net Primary Productivity 2022 (kg*C/m^2)", "Productividad Primaria Neta 2022 (kg*C/m^2)"],
    lblNPPTotal: ["NPP 2022 (total)", "NPP 2022 (total)"],
    lblNegTrend: ["- Trend", "Tendencia -"],
    lblNetLCChanges: ["Net LC Changes (ha)", "Cambios netos de CS (ha)"],
    lblNoData: ["No data", "Sin datos"],
    lblNoFeature: ["There is no feature at clicked point", "No hay ningún área de interés en el punto seleccionad"],
    lblNonKba: ["Non KBA", "No KBA"],
    lblNonProtectedAreas: ["Non Protected Areas", "Áreas No protegidas"],
    lblNonVegetatedArea: ["Non vegetated area", "Área sin vegetación"],
    lblNone: ["None", "Ninguna"],
    lblOpenInfoPanel: ["Open info panel", "Abrir panel informativo"],
    lblOtherLand: ["Other land", "Otras tierras"],
    lblPA1: ["Period Assesment 2016-2019 (1OAO)", "Evaluación de Período 2016-2019 (1OAO)"],
    lblPA2: ["Period Assesment 2016-2023 (1OAO)", "Evaluación de Período 2016-2023 (1OAO)"],
    lblPeriods: ["Periods", "Períodos"],
    lblPermissionDenied: ["User denied the request for Geolocation.", "El usuario denegó permisos para geolocalizar el dispositivo."],
    lblPosTrend: ["+ Trend", "Tendencia +"],
    lblPositionUnavailable: ["Location information is unavailable.", "La información de localización no está disponible."],
    lblPrecipitationTrend: ["Precipitation Trend 2010-2023", "Tendencia en las precipitaciones 2010-2023"],
    lblProcessing: ["Processing selected drawn-area for statistics, this might take a while...",
        "Procesando el área dibujada para obtener estadísticas, el proceso puede demorar..."],
    lblProcessingArea: ["Processing area, please wait...", "Procesando el área, por favor espere..."],
    lblProjectAreas: ["Project units", "Unidades de proyecto"],
    lblProtectedArea: ["Protected Area", "Área protegida"],
    lblProtectedAreas: ["Protected Areas", "Áreas protegidas"],
    lblProtectionKBA: ["Protection of KBAs", "Protección de KBAs"],
    lblRangelands: ["Rangelands", "Pastizales"],
    lblRemoveLocation: ["Remove marker", "Borrar marcador"],
    lblReset: ["Reset", "Reestablecer"],
    lblSAO2015: ["Status as of 2015 (Baseline-1OAO)", "Línea de base a partir de 2015 (Período Base-1OAO)"],
    lblSAO2019: ["Status as of 2019", "Situación a partir de 2019"],
    lblSAO2023: ["Status as of 2023", "Situación a partir de 2023"],
    lblSDG1531: ["SDG 15.3.1", "SDG 15.3.1"],
    lblSDG1531Title: ["SDG 15.3.1", "SDG 15.3.1"],
    lblSDGDegrading: ["Degradation", "Degradación"],
    lblSDGImproving: ["Improvement", "Mejora"],
    lblSDGStable: ["Stable", "Estable"],
    lblSOCTonnesHa: ["SOC tonnes/ha", "COS toneladas/ha"],
    lblSOCperLC: ["SOC mean per LC", "Carbono Org. Suelo x Uso"],
    lblSOCperLCLPD: ["SOC mean per LC/LPD", "Carbono Org. Suelo x Uso/Productividad"],
    lblSOCperLPD: ["SOC mean per LPD", "Carbono Org. Suelo x Productividad"],
    lblSelectAndCalculate: ["Select drawn-area & calculate  stats", "Seleccionar área dibujada y calcular estadísticas"],
    lblSelectArea: ["Please select an area.", "Seleccione un área por favor."],
    lblSelectContainer: ["Select Haiti", "Seleccionar Haití"],
    lblSelectGeometry: ["Please select a geometry first using the hand icon.", "Por favor seleccione una geometría primero utilizando el ícono de la mano."],
    lblSelectLayer: ["Please first select which layer you want to click on", "Por favor primero seleccione qué capa desea consultar"],
    lblSelectLevel1: ["Select governorate", "Seleccione governorate"],
    lblSelectLevel1First: ["Select governorate first", "Seleccione primero una pcia."],
    lblSelectLevel2: ["Select districts", "Seleccione municipios"],
    lblSelectedAOI: ["Selected area of interest", "Área de interés seleccionada"],
    lblSelectedAreaHa: ["Selected area: ", "Área seleccionada: "],
    lblSmallerArea: ["Please select area smaller than ", "Por favor seleccion un área menor a "],
    lblSnowIce: ["Snow/Ice", "Nieve/Hielo"],
    lblSocMap: ["Soil Organic Carbon", "Carbono Orgánico del Suelo"],
    lblSocMean: ["SOC Mean", "COS Promedio"],
    lblSocSum: ["SOC Stock", "COS Stock"],
    lblStable: ["Stable", "Estable"],
    lblStableButStressed: ["Stable but stressed", "Estable pero Estresado"],
    lblStepDisplay: ["Click 'Calculate' to preview layer, 'Reset' for new categories selection.",
        "Presione 'Calcular' para visualizar la capa, 'Reestablecer' para realizar una nueva combinación."],
    lblTableLC: ["Areas with Land Cover changes", "Áreas con cambios en el Uso"],
    lblTimeout: ["The request to get user location timed out.", "Finalizó el tiempo disponible para obtener la localización del usuario."],
    lblTopography: ["Topography", "Topografía"],
    lblTransitions: ["LC Transitions", "Transiciones de CS"],
    lblTreeCovered: ["Forest", "Bosque"],
    lblTrees: ["Trees", "Árboles"],
    lblUnexpectedError: ["Unexpected error occurred while processing geometry.", "Ha ocurrido un error inesperado procesando la geometría."],
    lblUnknownError: ["An unknown error occurred.", "Ha ocurrido un error inesperado."],
    lblUpdating: ["Updating", "Actualizando"],
    lblUserLocation: ["User location", "Localización de usuario"],
    lblVegetatedArea: ["Vegetated area", "Área con vegetación"],
    lblWater: ["Water", "Agua"],
    lblWaterbody: ["Water body", "Agua"],
    lblWetland: ["Wetland", "Humedal"],
    lblYear: ["Year", "Año"],
    lblDemoSites: ["Demonstration sites", "Sitios de muestreo"],
    lblLandscapes: ["Landscapes","Paisajes"],
    lblLCGLAD: ["GLAD", "GLAD"],
    
};

var languages = ["English", "Spanish"];
exports.languages = languages;

var getLocLabels = function (lan) {
    var loc = {};
    var index = languages.indexOf(lan);
    Object.keys(labels).forEach(function (key) {
        loc[key] = labels[key][index];
    });
    return loc;
};

exports.getLocLabels = getLocLabels;
exports.labels = labels;